# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from verdandi_codex.proto import verdandi_pb2 as verdandi__codex_dot_proto_dot_verdandi__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verdandi_codex/proto/verdandi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeIdentityServiceStub(object):
    """NodeIdentityService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/verdandi.NodeIdentityService/GetNodeInfo',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/verdandi.NodeIdentityService/Ping',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PingRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PingResponse.FromString,
                _registered_method=True)


class NodeIdentityServiceServicer(object):
    """NodeIdentityService
    """

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeIdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.NodeInfo.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PingRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verdandi.NodeIdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verdandi.NodeIdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeIdentityService(object):
    """NodeIdentityService
    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.NodeIdentityService/GetNodeInfo',
            verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.NodeIdentityService/Ping',
            verdandi__codex_dot_proto_dot_verdandi__pb2.PingRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthMetricsServiceStub(object):
    """HealthMetricsService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealthSnapshot = channel.unary_unary(
                '/verdandi.HealthMetricsService/GetHealthSnapshot',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.HealthSnapshot.FromString,
                _registered_method=True)
        self.WatchHealth = channel.unary_stream(
                '/verdandi.HealthMetricsService/WatchHealth',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.WatchHealthRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.HealthEvent.FromString,
                _registered_method=True)


class HealthMetricsServiceServicer(object):
    """HealthMetricsService
    """

    def GetHealthSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthMetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealthSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthSnapshot,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.HealthSnapshot.SerializeToString,
            ),
            'WatchHealth': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchHealth,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.WatchHealthRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.HealthEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verdandi.HealthMetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verdandi.HealthMetricsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthMetricsService(object):
    """HealthMetricsService
    """

    @staticmethod
    def GetHealthSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.HealthMetricsService/GetHealthSnapshot',
            verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.HealthSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/verdandi.HealthMetricsService/WatchHealth',
            verdandi__codex_dot_proto_dot_verdandi__pb2.WatchHealthRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.HealthEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryAndRegistryServiceStub(object):
    """DiscoveryAndRegistryService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKnownNodes = channel.unary_unary(
                '/verdandi.DiscoveryAndRegistryService/GetKnownNodes',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.KnownNodesResponse.FromString,
                _registered_method=True)
        self.WatchPresence = channel.unary_stream(
                '/verdandi.DiscoveryAndRegistryService/WatchPresence',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.WatchPresenceRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PresenceEvent.FromString,
                _registered_method=True)


class DiscoveryAndRegistryServiceServicer(object):
    """DiscoveryAndRegistryService
    """

    def GetKnownNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryAndRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKnownNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKnownNodes,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.KnownNodesResponse.SerializeToString,
            ),
            'WatchPresence': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPresence,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.WatchPresenceRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.PresenceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verdandi.DiscoveryAndRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verdandi.DiscoveryAndRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryAndRegistryService(object):
    """DiscoveryAndRegistryService
    """

    @staticmethod
    def GetKnownNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.DiscoveryAndRegistryService/GetKnownNodes',
            verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.KnownNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/verdandi.DiscoveryAndRegistryService/WatchPresence',
            verdandi__codex_dot_proto_dot_verdandi__pb2.WatchPresenceRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.PresenceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FabricGraphServiceStub(object):
    """FabricGraphService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFabricGraph = channel.unary_unary(
                '/verdandi.FabricGraphService/GetFabricGraph',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.GetFabricGraphRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.FabricGraphResponse.FromString,
                _registered_method=True)
        self.CreateAudioLink = channel.unary_unary(
                '/verdandi.FabricGraphService/CreateAudioLink',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.CreateAudioLinkRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
                _registered_method=True)
        self.CreateMidiLink = channel.unary_unary(
                '/verdandi.FabricGraphService/CreateMidiLink',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.CreateMidiLinkRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
                _registered_method=True)
        self.RemoveLink = channel.unary_unary(
                '/verdandi.FabricGraphService/RemoveLink',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.RemoveLinkRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
                _registered_method=True)
        self.GetLinkStatus = channel.unary_unary(
                '/verdandi.FabricGraphService/GetLinkStatus',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.GetLinkStatusRequest.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkStatusResponse.FromString,
                _registered_method=True)
        self.ListLinks = channel.unary_unary(
                '/verdandi.FabricGraphService/ListLinks',
                request_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
                response_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.ListLinksResponse.FromString,
                _registered_method=True)


class FabricGraphServiceServicer(object):
    """FabricGraphService
    """

    def GetFabricGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAudioLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMidiLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FabricGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFabricGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFabricGraph,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.GetFabricGraphRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.FabricGraphResponse.SerializeToString,
            ),
            'CreateAudioLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAudioLink,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.CreateAudioLinkRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.SerializeToString,
            ),
            'CreateMidiLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMidiLink,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.CreateMidiLinkRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.SerializeToString,
            ),
            'RemoveLink': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveLink,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.RemoveLinkRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.SerializeToString,
            ),
            'GetLinkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinkStatus,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.GetLinkStatusRequest.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.LinkStatusResponse.SerializeToString,
            ),
            'ListLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLinks,
                    request_deserializer=verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.FromString,
                    response_serializer=verdandi__codex_dot_proto_dot_verdandi__pb2.ListLinksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verdandi.FabricGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verdandi.FabricGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FabricGraphService(object):
    """FabricGraphService
    """

    @staticmethod
    def GetFabricGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/GetFabricGraph',
            verdandi__codex_dot_proto_dot_verdandi__pb2.GetFabricGraphRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.FabricGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAudioLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/CreateAudioLink',
            verdandi__codex_dot_proto_dot_verdandi__pb2.CreateAudioLinkRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMidiLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/CreateMidiLink',
            verdandi__codex_dot_proto_dot_verdandi__pb2.CreateMidiLinkRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/RemoveLink',
            verdandi__codex_dot_proto_dot_verdandi__pb2.RemoveLinkRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.LinkOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/GetLinkStatus',
            verdandi__codex_dot_proto_dot_verdandi__pb2.GetLinkStatusRequest.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.LinkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verdandi.FabricGraphService/ListLinks',
            verdandi__codex_dot_proto_dot_verdandi__pb2.Empty.SerializeToString,
            verdandi__codex_dot_proto_dot_verdandi__pb2.ListLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
